"""empty message

Revision ID: 06719b775dd1
Revises: e74db8b394e5
Create Date: 2024-08-07 17:43:48.812896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06719b775dd1'
down_revision = 'e74db8b394e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
